# Generated by Django 4.2.16 on 2024-10-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("min_quantity", models.IntegerField(blank=True, default=0)),
                ("current_quantity", models.IntegerField(blank=True, default=0)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (0, "Select Priority"),
                            (1, "Needed"),
                            (2, "Will need soon"),
                            (3, "Would be nice to have"),
                            (4, "It can wait"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "item_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping_list.list",
                    ),
                ),
            ],
        ),
    ]
