# Generated by Django 4.2.16 on 2024-10-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0002_alter_list_list_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="current_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="item",
            name="min_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (0, "Needed"),
                    (1, "Will need soon"),
                    (2, "Would be nice to have"),
                    (3, "It can wait"),
                ],
                default=0,
            ),
        ),
    ]
